const fs = require('fs');
let content = fs.readFileSync('src/App.tsx', 'utf8');

const mapping = {
  "React + TypeScript фронт": "React + TypeScript Front-end",
  "Backend на NestJS/Fastify": "NestJS/Fastify Backend",
  "Redis (кэш/события/скейл)": "Redis (Cache/Events/Scale)",
  "Мониторинг/логирование": "Monitoring/Logging",
  "Этот проект был пробным продуктом, и он дал главные уроки:": "This project was a pilot product, and it provided key lessons:",
  "в social/realtime играх важны не только фичи, а культура, комьюнити и экономика.": "in social/realtime games, not only features are important, but culture, community and economy.",
  "Но именно поэтому этот кейс крутой: он показывает, что я умею:": "But that's exactly why this case is cool: it shows what I can do:",
  "строить сложную систему,": "build a complex system,",
  "доводить до релиза,": "bring it to release,",
  "видеть слабые места продукта,": "see product weaknesses,",
  "и на следующей итерации делать уже правильнее (как в NOIR).": "and do it better in the next iteration (like in NOIR).",
  "NOIR — это премиальный социальный продукт в Telegram (TMA).": "NOIR is a premium social product in Telegram (TMA).",
  "Я хотел сделать не просто интерфейс, а цельную систему (на будущее):": "I wanted to make not just an interface, but a complete system (for the future):",
  "лента / контент / сценарии (чтобы было что делать),": "feed / content / scenarios (to have something to do),",
  "комьюнити и взаимодействия (чтобы было с кем),": "community and interactions (to have someone to do it with),",
  "слой доверия (чтобы не было мусора и токсичности),": "trust layer (so there is no garbage and toxicity),",
  "и всё это — в premium UX, как iOS-продукт.": "and all this — in a premium UX, like an iOS product.",
  "Я увидел простую проблему: большинство соц/знакомств в TWA/TMA — это мусорные клоны Tinder.": "I saw a simple problem: most social/dating 앱s in TWA/TMA are garbage Tinder clones.",
  "И я подумал: а если сделать продукт, который ощущается как нативное Apple-приложение, но живёт в Telegram?": "And I thought: what if we make a product that feels like a native Apple app, but lives in Telegram?",
  "TMA (Telegram Mini Apps) — это не просто мода, это платформа дистрибуции.": "TMA (Telegram Mini Apps) is not just a trend, it's a distribution platform.",
  "быстрый вход без установки,": "quick login without installation,",
  "привычная среда,": "familiar environment,",
  "легко масштабировать аудиторию,": "easy to scale audience,",
  "можно строить продукт прямо внутри мессенджера.": "you can build a product right inside the messenger.",
  "1) Концепт и Принципы": "1) Concept and Principles",
  "Сначала я зафиксировал архитектуру продукта, а не кода. Мои правила для NOIR:": "First I fixed the architecture of the product, not the code. My rules for NOIR:",
  "качество > количество": "quality > quantity",
  "меньше шума, больше смысла": "less noise, more meaning",
  "доверие и безопасность — часть архитектуры, а не фича": "trust and security are part of architecture, not a feature",
  "premium feel: скорость, микровзаимодействия, чистый UI": "premium feel: speed, microinteractions, clean UI",
  "2) UX/UI Система": "2) UX/UI System",
  "Я разложил продукт на состояния (пузыри, модалки, скелетоны, drawer-ы, action sheets) и компоненты.": "I broke the product down into states (bubbles, modals, skeletons, drawers, action sheets) and components.",
  "Цель была — сделать интерфейс бесшовным, с плавными переходами и 60fps анимациями.": "The goal was to make the interface seamless, with smooth transitions and 60fps animations.",
  "3) Дата-слой и Контракты": "3) Data Layer and Contracts",
  "Я сразу пошёл через дизайн API (Swagger/OpenAPI-first мышление). Сначала контракты, потом код.": "I went straight through API design (Swagger/OpenAPI-first mindset). Contracts first, then code.",
  "Это та часть, где full-stack мышление решает: я не жду бэкенд, я проектирую данные вместе с ним.": "This is the part where full-stack thinking rules: I don't wait for the backend, I design data with it.",
  "4) Архитектура Клиента (React + TS)": "4) Client Architecture (React + TS)",
  "Инженерный принцип: типа данных — король. Строгий TypeScript во всём приложении.": "Engineering principle: data type is king. Strict TypeScript throughout the application.",
  "TanStack Query (кэш, refetch)": "TanStack Query (cache, refetch)",
  "Zustand (локальные стейты)": "Zustand (local states)",
  "Redis (кэш/сессии/события)": "Redis (cache/sessions/events)",
  "Socket.io (опционально)": "Socket.io (optional)",
  "5) Безопасность и Инфраструктура": "5) Security and Infrastructure",
  "В NOIR я изначально закладывал production-ready практики:": "In NOIR, I initially laid down production-ready practices:",
  "верификация Telegram initData": "Telegram initData verification",
  "логирование критических операций и health checks": "logging critical operations and health checks",
  "контроль спама и rate limits": "spam control and rate limits",
  "миграции БД через Drizzle и мониторинг через Sentry": "DB migrations via Drizzle and monitoring via Sentry",
  "политика приватности данных": "data privacy policy",
  "6) Деплой и Релиз-цикл": "6) Deployment and Release Cycle",
  "Деплой я строю так, чтобы можно было катить фичи каждую неделю (Vite, Docker, CI/CD).": "I build deployment in such a way that features can be rolled out every week (Vite, Docker, CI/CD).",
  "В соц-продуктах важна не только разработка. Решает продуктовое видение и системный подход.": "In social products, not only development is important. Product vision and systemic approach decide.",
  "Что в этом кейсе самое сильное (что видно работодателю):": "What is strongest in this case (which is visible to the employer):",
  "системный UX (сценарии, удержание, понятные состояния)": "systematic UX (scenarios, retention, clear states)",
  "дизайн-система и premium UI": "design system and premium UI",
  "full-stack мышление (данные, контракты, инфраструктура)": "full-stack thinking (data, contracts, infrastructure)",
  "доверие/безопасность как часть архитектуры": "trust/security as part of architecture",
  "продакшн-подход: мониторинг, миграции, health checks": "production approach: monitoring, migrations, health checks",
  "Конфиденциально": "Confidential",
  "Проект закрыт и находится под NDA (Non-Disclosure Agreement). Я не могу раскрывать скриншоты, точные метрики или детали реализации.": "The project is closed and under NDA (Non-Disclosure Agreement). I cannot disclose screenshots, exact metrics, or implementation details.",
  "Я собрал систему, где ИИ-агенты работают как команда разработчиков, чтобы закрывать весь цикл создания фичи до написания кода.": "I assembled a system where AI agents work as a development team to cover the entire feature creation cycle before writing code.",
  "Цель — не «нагенерить код», а сделать так, чтобы разработка была предсказуемой и системной.": "The goal is not to 'generate code', but to make development predictable and systemic.",
  "В реальной разработке (особенно в стартапах) 80% времени уходит на коммуникацию и согласования:": "In real development (especially in startups) 80% of the time is spent on communication and approvals:",
  "задачи в хаосе и без чётких критериев «готово»,": "tasks in chaos and without clear 'done' criteria,",
  "долгое ревью и бесконечные правки,": "long review and endless edits,",
  "отсутствие артефактов (спеки, схемы, чеклисты, тесты),": "lack of artifacts (specs, schemas, checklists, tests),",
  "зависимость от «в голове держу».": "dependency on 'I keep it in my head'.",
  "Я хотел это убрать и сделать процесс таким, чтобы ИИ брал на себя всю черновую работу по системному анализу, проектированию иревью.": "I wanted to remove this and make the process such that AI takes over all the rough work on system analysis, design and review.",
  "Каждый агент — это отдельный скрипт с промптом и доступом к контексту (AST, схемы БД, файлы API).": "Each agent is a separate script with a prompt and access to context (AST, DB schemas, API files).",
  "{'>'} Output: Цель, сценарии использования, edge-cases и список рисков.": "{'>'} Output: Goal, use cases, edge-cases and list of risks.",
  "{'>'} Output: Структура модулей, контракты, машина состояний (XState/Mermaid).": "{'>'} Output: Modules structure, contracts, state machine (XState/Mermaid).",
  "{'>'} Output: Исходный код фичи, разбитый по компонентам и слоям.": "{'>'} Output: Source code of the feature, broken down by components and layers.",
  "{'>'} Output: PR Summary, список замечаний, автоматический fix простых issues.": "{'>'} Output: PR Summary, list of remarks, automatic fix of simple issues.",
  "{'>'} Output: Файлы .test.ts, моки данных, покрытие.": "{'>'} Output: .test.ts files, data mocks, coverage.",
  "{'>'} Output: Чеклист (миграции БД, новые ENV переменные, обновления документации).": "{'>'} Output: Checklist (DB migrations, new ENV variables, documentation updates).",
  "На выходе (для небольших фич) я получаю не просто «код», а готовый PR-набор:": "On the output (for small features) I get not just 'code', but a ready PR-kit:",
  "Спецификация + acceptance criteria": "Specification + acceptance criteria",
  "Схема потоков/состояний": "Diagram of flows/states",
  "Контракты API/событий": "API/events contracts",
  "PR summary и список рисков": "PR summary and list of risks",
  "Тест-скелет": "Test skeleton",
  "Релиз-чеклист": "Release checklist",
  "Скорость разработки растёт, потому что меньше времени тратится на согласования.": "Development speed grows because less time is spent on approvals.",
  "Качество не падает, потому что есть quality-gates на каждом этапе (спека -> схемы -> код).": "Quality does not fall because there are quality guards at every stage (specs -> circuits -> code).",
  "Процесс становится повторяемым: любая фича проходит один и тот же цикл независимо от того, кто её инициировал.": "The process becomes repeatable: any feature goes through the same cycle regardless of who initiated it.",
  "<strong>Меньше хаоса → меньше багов → быстрее time-to-market.</strong>": "<strong>Less chaos → fewer bugs → faster time-to-market.</strong>",
  "Я собрал pipeline для разработки с ИИ-агентами: спецификация, архитектура, код, ревью, тесты, релиз-чеклист.": "I built a pipeline for developing with AI agents: specs, architecture, code, tests, release checklists."
};


for (const [ru, en] of Object.entries(mapping)) {
    const escapedRu = ru.replace(/[.*+?^\\$\\(\\)|\\[\\]\\\\{}]/g, '\\\\$&');
    const regex1 = new RegExp(">(?:\\\\s*)(" + escapedRu + ")(?:\\\\s*)<", "g");
    
    content = content.replace(regex1, (match, p1) => {
        return match.replace(p1, "{i18n.language === 'en' ? '"+ en.replace(/'/g, "\\\\'") +"' : '"+ ru.replace(/'/g, "\\\\'") +"'}");
    });
}

fs.writeFileSync('src/App.tsx', content, 'utf8');
console.log('Done');
